// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEw9F4KV89rduukV-N5iO5uA_94hhECFo',
    appId: '1:541147176187:web:fc2c183316923375a5a45e',
    messagingSenderId: '541147176187',
    projectId: 'flutter-project-2a8a6',
    authDomain: 'flutter-project-2a8a6.firebaseapp.com',
    storageBucket: 'flutter-project-2a8a6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu3G4kfc7Ag29Qs1pQW4zISJbPyvxFxaY',
    appId: '1:541147176187:android:e3cc3be0d333f1aba5a45e',
    messagingSenderId: '541147176187',
    projectId: 'flutter-project-2a8a6',
    storageBucket: 'flutter-project-2a8a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMiq9a76osVi0bBmlwBzXBuSJzKNNHtwg',
    appId: '1:541147176187:ios:c4dba7a4c7420c2fa5a45e',
    messagingSenderId: '541147176187',
    projectId: 'flutter-project-2a8a6',
    storageBucket: 'flutter-project-2a8a6.appspot.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMiq9a76osVi0bBmlwBzXBuSJzKNNHtwg',
    appId: '1:541147176187:ios:dc8a6ff910cba8c2a5a45e',
    messagingSenderId: '541147176187',
    projectId: 'flutter-project-2a8a6',
    storageBucket: 'flutter-project-2a8a6.appspot.com',
    iosBundleId: 'com.example.flutterProject.RunnerTests',
  );
}
